Btcd support
jamaljsr/polar pull request #1092
Opened 2024-12-30 20:45 UTC by Abdulkbk

Closes #302 

### Description

This pull request introduces support for the BTCD node implementation to Polar. (More details will be added soon)

### Steps to Test

1. Steps
2. To
3. Test

### Screenshots

[Only if applicable]

2025-01-03 17:03 UTC, jamaljsr commented
Hey @Abdulkbk thanks for opening this draft PR to show what you've implemented so far. I skimmed through the diff and so far it's looking fantastic! I'm pleasantly surprised to see the test coverage still at 100%.  👌

Please let me know if you have any questions or need any assistance moving forward with this.

2025-01-06 09:10 UTC, Abdulkbk commented
Hey @jamaljsr thanks for taking the time to skim through this.

> I'm pleasantly surprised to see the test coverage still at 100%.

Yes, I try to add test to all new code as I add them👌.


> Please let me know if you have any questions or need any assistance moving forward with this.

Of course I will. I've been thinking of the best way I should add the`btcdservice` but I'm inclined towards using `REST` as I couldn't find a standard library similar to the one used for `bitcoindService`.

2025-01-15 18:34 UTC, Abdulkbk commented
Hey @jamaljsr, I am currently facing two blockers. I figured out a way for the first but I am still figuring out the second.

The first is that BTCD has wallet functionalities [decoupled](https://github.com/btcsuite/btcd/blob/09ba026580f4041bae30d732f26fa1a2036af003/docs/json_rpc_api.md?plain=1#L33) from chain functionalities, unlike `bitcoind`. However, there are workarounds. For example, I can run BTCD alongside `btcwallet`, and then use `btcwallet` for all non-CLI calls, as it supports both chain and wallet-related [RPCs](https://github.com/btcsuite/btcd/blob/09ba026580f4041bae30d732f26fa1a2036af003/docs/json_rpc_api.md?plain=1#L38).

The second blocker is that `btcwallet` [does not support regtest](https://github.com/btcsuite/btcwallet/issues/955) currently, meanwhile all the other node implementations in Polar use regtest. I think this is the real challenge.

I would love to hear your thoughts as I continue to figure a way out. Thanks.

2025-01-16 06:30 UTC, jamaljsr commented
Hi @Abdulkbk,  

> The second blocker is that `btcwallet` [does not support regtest](https://github.com/btcsuite/btcwallet/issues/955) currently, meanwhile all the other node implementations in Polar use regtest. I think this is the real challenge.
> 
> I would love to hear your thoughts as I continue to figure a way out. Thanks.

Oh wow, you are correct! `btcd` uses a different network for local testing called `simnet`. I totally forgot about this. While `lnd` does have support for simnet, the other implementations do not AFAIK. So if we move forward, we'd have to prevent adding CLN/Eclair nodes when there is no `bitcoind` present in the network. We'd also have to prevent mixing `btcd` and `bitcoind` in the same network since they won't be able to communicate with each other. This problem is going to really increase the effort required for this PR substantially due to the added compatibility complexity. 

I honestly don't have all the answers right now on how to implement this best, but I'm willing to work with you if you are still interested in pursuing this. My hunch is that there will be more challenges along the way. We'll likely need to split this up into multiple PRs so reviewing the updates won't be too difficult. Let me know if you'd like to continue with this. I'd totally understand if this feels like too large of a project to tackle at this time.

2025-01-16 11:54 UTC, Abdulkbk commented
> This problem is going to really increase the effort required for this PR substantially due to the added compatibility complexity.

I agree this will require much more effort.

> We'll likely need to split this up into multiple PRs so reviewing the updates won't be too difficult. Let me know if you'd like to continue with this. I'd totally understand if this feels like too large of a project to tackle at this time.

I would like to take this further. I will perhaps start by modifying this PR to focus on refactoring the implementation of the Bitcoin nodes to use a factory. Once I’ve completed that, I will request a review.

2025-01-20 21:25 UTC, Abdulkbk commented
Hey @jamaljsr, I think this PR is ready for reviews. Thanks

2025-01-27 05:43 UTC, jamaljsr requested changes
@Abdulkbk Thank you very much for the updates to this PR. This is very well done. I wouldn't have done it any different myself. I really appreciate this update. 🙏

This looks good to go with just one small interface to cleanup. I'll be happy to merge this after that change.

2025-01-27 05:43 UTC, jamaljsr commented on src/types/index.ts
> +export interface BitcoinService {
Can you delete the `BitcoindLibrary` interface above since this one replaces it and that one is no longer being used?

2025-01-27 14:15 UTC, Abdulkbk commented on src/types/index.ts
> +export interface BitcoinService {
I just removed it [here](https://github.com/jamaljsr/polar/pull/1092/commits/49c1e3d412175ba3fb9bd08517cfe222c1c4f54e#diff-a9ba9cbedd19c9f66d564d2e89912890209b98f0a7ef19187877d2587300e476L147). Since we phased it out from the tests in 49c1e3d412175ba3fb9bd08517cfe222c1c4f54e commit

2025-01-27 14:21 UTC, Abdulkbk commented on src/lib/bitcoin/bitcoind/bitcoindService.ts
> +      host: `127.0.0.1`,
I want also to inform you @jamaljsr  that `bitcoind` could not connect after this change until I made this modification.

![Screenshot from 2025-01-27 14-20-51](https://github.com/user-attachments/assets/bed3e002-c934-4d63-a639-6947313b6f13)

Before:
```js
return new BitcoinCore({
      host: `http://127.0.0.1:${node.ports.rpc}`,
      username: bitcoinCredentials.user,
      password: bitcoinCredentials.pass,
      logger: this.log(),
      // use a long timeout due to the time it takes to mine a lot of blocks
      timeout: 5 * 60 * 1000,
    });
```

After:

```js
return new BitcoinCore({
      host: `127.0.0.1`,
      port: node.ports.rpc,
      username: bitcoinCredentials.user,
      password: bitcoinCredentials.pass,
      logger: this.log(),
      // use a long timeout due to the time it takes to mine a lot of blocks
      timeout: 5 * 60 * 1000,
    });
```

2025-01-27 19:12 UTC, jamaljsr commented on src/lib/bitcoin/bitcoind/bitcoindService.ts
> +      host: `127.0.0.1`,
Yes, the `bitcoin-core` package was updated to v5 by the bot in #1115. This was a breaking change that I fixed by modifying the constructor args. You'll need to run `yarn install` to ensure you have the latest package version which should fix the connection error without a code change.

2025-01-27 19:34 UTC, Abdulkbk commented on src/lib/bitcoin/bitcoind/bitcoindService.ts
> +      host: `127.0.0.1`,
> Yes, the `bitcoin-core` package was updated to v5 by the bot in #1115. This was a breaking change that I fixed in `master` by modifying the constructor args. You'll need to run `yarn install` to ensure you have the latest package version after the rebase, which should fix the connection error without a code change.

I just ran `yarn install` after the rebase and the connection worked without the modification. I have removed this modification now.

2025-01-27 20:02 UTC, jamaljsr approved these changes
LGTM 💪

2025-01-27 20:02 UTC, merged